"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import ssl
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote

import environ
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

env = environ.Env(
    DEBUG=(bool, True),
    ALLOW_DEV_LIFECYCLE_FIXTURE=(bool, False),
    ALLOW_DEV_SESSION_BOOTSTRAP=(bool, False),
    CELERY_TASK_ALWAYS_EAGER=(bool, True),
    USE_AZURE_REDIS=(bool, False),
    PUBLIC_AUTH_EMAIL_BACKEND=(str, "disabled"),
    TICKET_COMPLETION_CAPSULE_BACKEND=(str, "disabled"),
    TICKET_COMPLETION_CAPSULE_TEST_MODE=(bool, False),
    TICKET_COMPLETION_EMAIL_BACKEND=(str, "disabled"),
    TICKET_ATTACHMENT_STORAGE_BACKEND=(str, "disabled"),
    TICKET_ATTACHMENT_STORAGE_TEST_MODE=(bool, False),
    TICKET_ATTACHMENT_MAX_BYTES=(int, 0),
    TICKET_ATTACHMENT_ALLOWED_CONTENT_TYPES=(list, []),
    TICKET_ATTACHMENT_UPLOAD_URL_EXPIRY_SECONDS=(int, 900),
)
environ.Env.read_env(PROJECT_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="local-only-change-before-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
ALLOW_DEV_LIFECYCLE_FIXTURE = env("ALLOW_DEV_LIFECYCLE_FIXTURE")
ALLOW_DEV_SESSION_BOOTSTRAP = env("ALLOW_DEV_SESSION_BOOTSTRAP")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'phonenumber_field',
    'apps.authentication.apps.AuthenticationConfig',
    'apps.identity.apps.IdentityConfig',
    'apps.platform_access.apps.PlatformAccessConfig',
    'apps.tenancy.apps.TenancyConfig',
    'apps.tickets.apps.TicketsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.platform_access.middleware.PlatformAccessDenialAuditMiddleware',
    'apps.platform_access.middleware.EngineWatermarkMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

postgres_host = env("PGHOST", default="")
postgres_password = env("PGPASSWORD", default="")
if postgres_host and postgres_password:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": postgres_host,
            "PORT": env.int("PGPORT", default=5432),
            "NAME": env("PGDATABASE"),
            "USER": env("PGUSER"),
            "PASSWORD": postgres_password,
            "OPTIONS": {
                "sslmode": env("PGSSLMODE", default="require"),
                "connect_timeout": env.int("PGCONNECT_TIMEOUT", default=10),
            },
        }
    }
else:
    DATABASES = {
        "default": env.db(
            "DATABASE_URL",
            default="postgresql://nivasops:nivasops@127.0.0.1:5432/nivasops",
        )
    }
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DATABASE_CONN_MAX_AGE", default=0)
DATABASES["default"]["ATOMIC_REQUESTS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "identity.User"
PHONENUMBER_DB_FORMAT = "E164"
PHONENUMBER_DEFAULT_REGION = None


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost:3000"])
CORS_ALLOW_HEADERS = [
    *default_headers,
    "x-society-id",
    "idempotency-key",
    "x-client-signature",
]
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://localhost:3000"])
PUBLIC_AUTH_FRONTEND_ORIGIN = env(
    "PUBLIC_AUTH_FRONTEND_ORIGIN",
    default="http://localhost:3000",
)
PUBLIC_AUTH_EMAIL_BACKEND = env("PUBLIC_AUTH_EMAIL_BACKEND")
ACS_EMAIL_ENDPOINT = env("ACS_EMAIL_ENDPOINT", default="")
ACS_EMAIL_SENDER = env("ACS_EMAIL_SENDER", default="")
TICKET_COMPLETION_CAPSULE_BACKEND = env("TICKET_COMPLETION_CAPSULE_BACKEND")
TICKET_COMPLETION_KEY_VAULT_URL = env("TICKET_COMPLETION_KEY_VAULT_URL", default="")
TICKET_COMPLETION_CAPSULE_TEST_MODE = env("TICKET_COMPLETION_CAPSULE_TEST_MODE")
TICKET_COMPLETION_EMAIL_BACKEND = env("TICKET_COMPLETION_EMAIL_BACKEND")
TICKET_ATTACHMENT_STORAGE_BACKEND = env("TICKET_ATTACHMENT_STORAGE_BACKEND")
TICKET_ATTACHMENT_STORAGE_TEST_MODE = env("TICKET_ATTACHMENT_STORAGE_TEST_MODE")
TICKET_ATTACHMENT_MAX_BYTES = env("TICKET_ATTACHMENT_MAX_BYTES")
TICKET_ATTACHMENT_ALLOWED_CONTENT_TYPES = env("TICKET_ATTACHMENT_ALLOWED_CONTENT_TYPES")
TICKET_ATTACHMENT_UPLOAD_URL_EXPIRY_SECONDS = env(
    "TICKET_ATTACHMENT_UPLOAD_URL_EXPIRY_SECONDS"
)
AZURE_STORAGE_ACCOUNT_NAME = env("AZURE_STORAGE_ACCOUNT_NAME", default="")
AZURE_STORAGE_ACCOUNT_KEY = env("AZURE_STORAGE_ACCOUNT_KEY", default="")
AZURE_STORAGE_BLOB_ENDPOINT = env("AZURE_STORAGE_BLOB_ENDPOINT", default="")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.authentication.backends.TenantJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": env("JWT_ALGORITHM", default="HS256"),
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default=SECRET_KEY),
    "VERIFYING_KEY": env("JWT_VERIFYING_KEY", default=""),
    "AUDIENCE": env("JWT_AUDIENCE", default="nivasops-clients"),
    "ISSUER": env("JWT_ISSUER", default="nivasops-api"),
    "LEEWAY": 5,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "NivasOps API",
    "DESCRIPTION": "Multi-tenant helpdesk and facility operations API.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "EXTENSIONS_INFO": {
        "x-engine": "NivasOps Core",
        "x-provenance": "https://github.com/sushamnandi2468/Nivas",
        "x-signature": "7b3f94e1-2a8d-5e63-91c7-d4f092b1a852",
        "x-license": "AGPL-3.0-or-later",
    },
}

azure_redis_host = env("AZURE_REDIS_HOST", default="")
azure_redis_access_key = env("AZURE_REDIS_ACCESS_KEY", default="")
azure_redis_port = env.int("AZURE_REDIS_PORT", default=6380)
use_azure_redis = env("USE_AZURE_REDIS")
azure_redis_use_single_database = env.bool(
    "AZURE_REDIS_USE_SINGLE_DATABASE", default=(azure_redis_port == 10000)
)


def azure_redis_url(database):
    encoded_access_key = quote(azure_redis_access_key, safe="")
    target_database = 0 if azure_redis_use_single_database else database
    return f"rediss://:{encoded_access_key}@{azure_redis_host}:{azure_redis_port}/{target_database}"


if use_azure_redis and (not azure_redis_host or not azure_redis_access_key):
    raise ImproperlyConfigured(
        "USE_AZURE_REDIS requires AZURE_REDIS_HOST and AZURE_REDIS_ACCESS_KEY."
    )

if use_azure_redis:
    CELERY_BROKER_URL = azure_redis_url(0)
    CELERY_RESULT_BACKEND = azure_redis_url(1)
    CACHE_URL = azure_redis_url(2)
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
else:
    CELERY_BROKER_URL = env(
        "CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0"
    )
    CELERY_RESULT_BACKEND = env(
        "CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/1"
    )
    CACHE_URL = env("CACHE_URL", default="")

CELERY_BROKER_TRANSPORT_OPTIONS = {"global_keyprefix": "nivasops:broker:"}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {"global_keyprefix": "nivasops:result:"}
CELERY_TASK_ALWAYS_EAGER = env("CELERY_TASK_ALWAYS_EAGER")
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TIMEZONE = "UTC"

if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_URL,
            "KEY_PREFIX": "nivasops",
            "OPTIONS": {
                "ssl_cert_reqs": ssl.CERT_REQUIRED,
            }
            if CACHE_URL.startswith("rediss://")
            else {},
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "nivasops-development",
            "KEY_PREFIX": "nivasops",
        }
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {"handlers": ["console"], "level": env("LOG_LEVEL", default="INFO")},
}
