# Generated by Django 5.2.17 on 2026-08-25 20:41

import apps.identity.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_code', models.CharField(max_length=64, unique=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64, validators=[apps.identity.models.validate_iana_timezone])),
                ('locale', models.CharField(default='en-IN', max_length=16)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('retention_policy', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_society',
                'ordering': ('registration_code',),
            },
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('FACILITY_MANAGER', 'Facility manager'), ('ESTATE_SUPERVISOR', 'Estate supervisor'), ('HELPDESK_OPERATOR', 'Helpdesk operator')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to='tenancy.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancy_staff_membership',
                'ordering': ('society_id', 'user_id', 'starts_at'),
                'constraints': [models.UniqueConstraint(fields=('society', 'id'), name='tenancy_staff_society_id_uniq'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'user'), name='tenancy_staff_one_active_uniq'), models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='tenancy_staff_valid_period')],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_staff_membership ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_staff_membership FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_staff_society_isolation
                ON tenancy_staff_membership
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_staff_society_isolation
                    ON tenancy_staff_membership;
                ALTER TABLE tenancy_staff_membership NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_staff_membership DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
