# Generated by Django 5.2.17 on 2026-08-26 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='tenancy.society')),
            ],
            options={
                'db_table': 'tenancy_block',
                'ordering': ('society_id', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_areas', to='tenancy.society')),
            ],
            options={
                'db_table': 'tenancy_common_area',
                'ordering': ('society_id', 'normalized_name'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('door_number', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='tenancy.block')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='tenancy.society')),
            ],
            options={
                'db_table': 'tenancy_unit',
                'ordering': ('society_id', 'block_id', 'door_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tenancy_block_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('society', 'code'), name='tenancy_block_society_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='commonarea',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tenancy_common_area_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='commonarea',
            constraint=models.UniqueConstraint(fields=('society', 'normalized_name'), name='tenancy_common_area_society_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tenancy_unit_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('society', 'block', 'door_number'), name='tenancy_unit_society_block_door_uniq'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_unit
                ADD CONSTRAINT tenancy_unit_society_block_fk
                FOREIGN KEY (society_id, block_id)
                REFERENCES tenancy_block (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_block ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_block FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_common_area ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_common_area FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_block_society_isolation
                ON tenancy_block
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tenancy_common_area_society_isolation
                ON tenancy_common_area
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tenancy_unit_society_isolation
                ON tenancy_unit
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_unit_society_isolation
                    ON tenancy_unit;
                ALTER TABLE tenancy_unit NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tenancy_common_area_society_isolation
                    ON tenancy_common_area;
                ALTER TABLE tenancy_common_area NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_common_area DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tenancy_block_society_isolation
                    ON tenancy_block;
                ALTER TABLE tenancy_block NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_block DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit
                    DROP CONSTRAINT IF EXISTS tenancy_unit_society_block_fk;
            """,
        ),
    ]
