# Generated by Django 5.2.17 on 2026-08-26 10:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_block_commonarea_unit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRESIDENT", "President"),
                            ("SECRETARY", "Secretary"),
                            ("TREASURER", "Treasurer"),
                            ("MEMBER", "Member"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committee_memberships",
                        to="tenancy.society",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="committee_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_committee_membership",
                "ordering": ("society_id", "user_id", "starts_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "id"), name="tenancy_committee_society_id_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("society", "user"),
                        name="tenancy_committee_one_active_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="tenancy_committee_valid_period",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitOccupancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occupancy_type",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("TENANT", "Tenant"),
                            ("FAMILY", "Family member"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("can_approve_costs", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_occupancies",
                        to="tenancy.society",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupancies",
                        to="tenancy.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_occupancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_unit_occupancy",
                "ordering": ("society_id", "unit_id", "starts_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "id"), name="tenancy_occupancy_society_id_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("society", "unit", "user"),
                        name="tenancy_occupancy_one_active_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="tenancy_occupancy_valid_period",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_unit_occupancy
                ADD CONSTRAINT tenancy_occupancy_society_unit_fk
                FOREIGN KEY (society_id, unit_id)
                REFERENCES tenancy_unit (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_committee_membership ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_committee_membership FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit_occupancy ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit_occupancy FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_committee_society_isolation
                ON tenancy_committee_membership
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tenancy_occupancy_society_isolation
                ON tenancy_unit_occupancy
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_occupancy_society_isolation
                    ON tenancy_unit_occupancy;
                ALTER TABLE tenancy_unit_occupancy NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit_occupancy DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tenancy_committee_society_isolation
                    ON tenancy_committee_membership;
                ALTER TABLE tenancy_committee_membership NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_committee_membership DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_unit_occupancy
                    DROP CONSTRAINT IF EXISTS tenancy_occupancy_society_unit_fk;
            """,
        ),
    ]
