# Generated by Django 5.2.17 on 2026-08-26 10:22

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import apps.tenancy.models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_committeemembership_unitoccupancy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "invitee_phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            ("STAFF", "Staff"),
                            ("RESIDENT", "Resident"),
                            ("COMMITTEE", "Committee"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "occupancy_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("TENANT", "Tenant"),
                            ("FAMILY", "Family member"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "staff_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACILITY_MANAGER", "Facility manager"),
                            ("ESTATE_SUPERVISOR", "Estate supervisor"),
                            ("HELPDESK_OPERATOR", "Helpdesk operator"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "committee_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESIDENT", "President"),
                            ("SECRETARY", "Secretary"),
                            ("TREASURER", "Treasurer"),
                            ("MEMBER", "Member"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.tenancy.models.default_invitation_expiry),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_membership_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_membership_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_membership_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_invitations",
                        to="tenancy.society",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_invitations",
                        to="tenancy.unit",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_membership_invitation",
                "ordering": ("society_id", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["society", "status", "expires_at"], name="tenancy_invite_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "id"), name="tenancy_invite_society_id_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("persona", "RESIDENT"), ("status", "PENDING")),
                        fields=("society", "invitee_phone", "persona", "unit"),
                        name="tenancy_invite_pending_resident_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "PENDING"), models.Q(("persona", "RESIDENT"), _negated=True)
                        ),
                        fields=("society", "invitee_phone", "persona"),
                        name="tenancy_invite_pending_role_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("committee_role__isnull", True),
                                ("occupancy_type__isnull", False),
                                ("persona", "RESIDENT"),
                                ("staff_role__isnull", True),
                                ("unit__isnull", False),
                            ),
                            models.Q(
                                ("committee_role__isnull", True),
                                ("occupancy_type__isnull", True),
                                ("persona", "STAFF"),
                                ("staff_role__isnull", False),
                                ("unit__isnull", True),
                            ),
                            models.Q(
                                ("committee_role__isnull", False),
                                ("occupancy_type__isnull", True),
                                ("persona", "COMMITTEE"),
                                ("staff_role__isnull", True),
                                ("unit__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="tenancy_invite_payload_matches_persona",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                                ("status", "PENDING"),
                            ),
                            models.Q(
                                ("accepted_at__isnull", False),
                                ("accepted_by__isnull", False),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                                ("status", "ACCEPTED"),
                            ),
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                                ("status", "REVOKED"),
                            ),
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                                ("status", "EXPIRED"),
                            ),
                            _connector="OR",
                        ),
                        name="tenancy_invite_status_timestamps",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_membership_invitation
                ADD CONSTRAINT tenancy_invite_society_unit_fk
                FOREIGN KEY (society_id, unit_id)
                REFERENCES tenancy_unit (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_membership_invitation ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_membership_invitation FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_invite_society_isolation
                ON tenancy_membership_invitation
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_invite_society_isolation
                    ON tenancy_membership_invitation;
                ALTER TABLE tenancy_membership_invitation NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_membership_invitation DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_membership_invitation
                    DROP CONSTRAINT IF EXISTS tenancy_invite_society_unit_fk;
            """,
        ),
    ]
