# Generated by Django 5.2.17 on 2026-08-26 10:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0004_membershipinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_active_tickets", models.PositiveIntegerField(default=5)),
                ("current_active_tickets_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technician_profiles",
                        to="tenancy.society",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technician_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_technician_profile",
                "ordering": ("society_id", "user_id", "starts_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "id"), name="tenancy_technician_society_id_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("society", "user"),
                        name="tenancy_technician_one_active_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="tenancy_technician_valid_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_active_tickets__gt", 0)),
                        name="tenancy_technician_positive_capacity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("current_active_tickets_count__lte", models.F("max_active_tickets"))
                        ),
                        name="tenancy_technician_capacity_not_exceeded",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_technician_profile ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_technician_profile FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_technician_society_isolation
                ON tenancy_technician_profile
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_technician_society_isolation
                    ON tenancy_technician_profile;
                ALTER TABLE tenancy_technician_profile NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_technician_profile DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
