# Generated by Django 5.2.17 on 2026-08-26 11:24

import uuid

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0005_technicianprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("normalized_company_name", models.CharField(editable=False, max_length=255)),
                ("contact_person", models.CharField(max_length=128)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="tenancy.society",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_vendor",
                "ordering": ("society_id", "normalized_company_name"),
            },
        ),
        migrations.CreateModel(
            name="VendorContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_active_tickets", models.PositiveIntegerField(blank=True, null=True)),
                ("current_active_tickets_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_contracts",
                        to="tenancy.society",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="tenancy.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_vendor_contract",
                "ordering": ("society_id", "vendor_id", "starts_on"),
            },
        ),
        migrations.CreateModel(
            name="VendorStaffMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("DISPATCHER", "Dispatcher"), ("WORKER", "Worker")], max_length=16
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_memberships",
                        to="tenancy.vendorcontract",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_staff_memberships",
                        to="tenancy.society",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_staff_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_memberships",
                        to="tenancy.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_vendor_staff_membership",
                "ordering": ("society_id", "vendor_id", "user_id", "starts_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("society", "id"), name="tenancy_vendor_society_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("society", "normalized_company_name"),
                name="tenancy_vendor_society_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.UniqueConstraint(
                fields=("society", "id"), name="tenancy_vendor_contract_society_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="tenancy_vendor_contract_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_active_tickets__isnull", True),
                    ("max_active_tickets__gt", 0),
                    _connector="OR",
                ),
                name="tenancy_vendor_contract_positive_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_active_tickets__isnull", True),
                    ("current_active_tickets_count__lte", models.F("max_active_tickets")),
                    _connector="OR",
                ),
                name="tenancy_vendor_contract_capacity_not_exceeded",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorstaffmembership",
            constraint=models.UniqueConstraint(
                fields=("society", "id"), name="tenancy_vendor_staff_society_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorstaffmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("society", "contract", "user"),
                name="tenancy_vendor_staff_one_active_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorstaffmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="tenancy_vendor_staff_valid_period",
            ),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tenancy_vendor_contract
                ADD CONSTRAINT tenancy_vendor_contract_society_vendor_fk
                FOREIGN KEY (society_id, vendor_id)
                REFERENCES tenancy_vendor (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_vendor_staff_membership
                ADD CONSTRAINT tenancy_vendor_staff_society_vendor_fk
                FOREIGN KEY (society_id, vendor_id)
                REFERENCES tenancy_vendor (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_vendor_staff_membership
                ADD CONSTRAINT tenancy_vendor_staff_society_contract_fk
                FOREIGN KEY (society_id, contract_id)
                REFERENCES tenancy_vendor_contract (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tenancy_vendor ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_contract ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_contract FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_staff_membership ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_staff_membership FORCE ROW LEVEL SECURITY;

                CREATE POLICY tenancy_vendor_society_isolation
                ON tenancy_vendor
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tenancy_vendor_contract_society_isolation
                ON tenancy_vendor_contract
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tenancy_vendor_staff_society_isolation
                ON tenancy_vendor_staff_membership
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenancy_vendor_staff_society_isolation
                    ON tenancy_vendor_staff_membership;
                ALTER TABLE tenancy_vendor_staff_membership NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_staff_membership DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tenancy_vendor_contract_society_isolation
                    ON tenancy_vendor_contract;
                ALTER TABLE tenancy_vendor_contract NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_contract DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tenancy_vendor_society_isolation
                    ON tenancy_vendor;
                ALTER TABLE tenancy_vendor NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tenancy_vendor_staff_membership
                    DROP CONSTRAINT IF EXISTS tenancy_vendor_staff_society_contract_fk;
                ALTER TABLE tenancy_vendor_staff_membership
                    DROP CONSTRAINT IF EXISTS tenancy_vendor_staff_society_vendor_fk;
                ALTER TABLE tenancy_vendor_contract
                    DROP CONSTRAINT IF EXISTS tenancy_vendor_contract_society_vendor_fk;
            """,
        ),
    ]
