# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0006_vendor_vendorcontract_vendorstaffmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipinvitation",
            name="invitee_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]