# Generated by Django 5.2.17 on 2026-08-26 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128)),
                ('workflow_type', models.CharField(choices=[('SERVICE', 'Service'), ('GOVERNANCE', 'Governance')], max_length=16)),
                ('allows_unit_location', models.BooleanField(default=False)),
                ('allows_common_area_location', models.BooleanField(default=False)),
                ('allows_no_location', models.BooleanField(default=False)),
                ('cost_responsibility', models.CharField(choices=[('RESIDENT_UNIT', 'Resident unit'), ('SOCIETY', 'Society'), ('NO_CHARGE', 'No charge')], max_length=16)),
                ('completion_policy', models.CharField(choices=[('RESIDENT_CONFIRMATION', 'Resident confirmation'), ('GOVERNANCE_RESOLUTION', 'Governance resolution')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_categories', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_ticket_category',
                'ordering': ('society_id', 'normalized_name'),
            },
        ),
        migrations.CreateModel(
            name='TicketSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(editable=False, max_length=128)),
                ('default_priority', models.CharField(choices=[('P1', 'P1 Critical'), ('P2', 'P2 High'), ('P3', 'P3 Medium'), ('P4', 'P4 Low')], default='P3', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='tickets.ticketcategory')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_subcategories', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_ticket_subcategory',
                'ordering': ('society_id', 'category_id', 'normalized_name'),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, default='', max_length=32)),
                ('workflow_type', models.CharField(choices=[('SERVICE', 'Service'), ('GOVERNANCE', 'Governance')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('P1', 'P1 Critical'), ('P2', 'P2 High'), ('P3', 'P3 Medium'), ('P4', 'P4 Low')], max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('PENDING_ESTIMATE_APPROVAL', 'Pending estimate approval'), ('PENDING_RESIDENT_CONFIRMATION', 'Pending resident confirmation'), ('SUPERVISOR_TRIAGE', 'Supervisor triage'), ('UNDER_REVIEW', 'Under review'), ('IN_DISCUSSION', 'In discussion'), ('ACTION_TAKEN', 'Action taken'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('MERGED', 'Merged')], default='DRAFT', max_length=32)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenancy.commonarea')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenancy.society')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenancy.unit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketsubcategory')),
            ],
            options={
                'db_table': 'tickets_ticket',
                'ordering': ('society_id', '-created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_category_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(fields=('society', 'id', 'workflow_type'), name='tickets_category_society_workflow_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(fields=('society', 'normalized_name'), name='tickets_category_society_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(('allows_unit_location', True), ('allows_common_area_location', True), ('allows_no_location', True), _connector='OR'), name='tickets_category_has_location_policy'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allows_no_location', False), ('completion_policy', 'RESIDENT_CONFIRMATION'), ('workflow_type', 'SERVICE')), models.Q(('completion_policy', 'GOVERNANCE_RESOLUTION'), ('workflow_type', 'GOVERNANCE')), _connector='OR'), name='tickets_category_workflow_completion'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost_responsibility', 'RESIDENT_UNIT'), _negated=True), models.Q(('allows_unit_location', True), ('workflow_type', 'SERVICE')), _connector='OR'), name='tickets_category_resident_cost_unit'),
        ),
        migrations.AddConstraint(
            model_name='ticketsubcategory',
            constraint=models.UniqueConstraint(fields=('society', 'category', 'id'), name='tickets_subcategory_society_category_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketsubcategory',
            constraint=models.UniqueConstraint(fields=('society', 'category', 'normalized_name'), name='tickets_subcategory_society_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_ticket_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_number', ''), _negated=True), fields=('society', 'ticket_number'), name='tickets_ticket_society_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('state_version__gte', 1)), name='tickets_ticket_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('unit__isnull', True), ('common_area__isnull', True), _connector='OR'), name='tickets_ticket_at_most_one_location'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_type', 'GOVERNANCE'), ('unit__isnull', False), ('common_area__isnull', False), _connector='OR'), name='tickets_service_requires_location'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('DRAFT', 'SUBMITTED', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'PENDING_ESTIMATE_APPROVAL', 'PENDING_RESIDENT_CONFIRMATION', 'SUPERVISOR_TRIAGE', 'RESOLVED', 'CLOSED', 'CANCELLED', 'MERGED')), ('workflow_type', 'SERVICE')), models.Q(('status__in', ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'IN_DISCUSSION', 'ACTION_TAKEN', 'RESOLVED', 'CLOSED', 'CANCELLED', 'MERGED')), ('workflow_type', 'GOVERNANCE')), _connector='OR'), name='tickets_ticket_workflow_status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('submitted_at__isnull', True), ('ticket_number', '')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('ticket_number', ''), _negated=True), ('submitted_at__isnull', False)), _connector='OR'), name='tickets_ticket_submission_metadata'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_ticket_subcategory
                ADD CONSTRAINT tickets_subcategory_society_category_fk
                FOREIGN KEY (society_id, category_id)
                REFERENCES tickets_ticket_category (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket
                ADD CONSTRAINT tickets_ticket_society_category_workflow_fk
                FOREIGN KEY (society_id, category_id, workflow_type)
                REFERENCES tickets_ticket_category (society_id, id, workflow_type)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket
                ADD CONSTRAINT tickets_ticket_society_subcategory_fk
                FOREIGN KEY (society_id, category_id, subcategory_id)
                REFERENCES tickets_ticket_subcategory (society_id, category_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket
                ADD CONSTRAINT tickets_ticket_society_unit_fk
                FOREIGN KEY (society_id, unit_id)
                REFERENCES tenancy_unit (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket
                ADD CONSTRAINT tickets_ticket_society_common_area_fk
                FOREIGN KEY (society_id, common_area_id)
                REFERENCES tenancy_common_area (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_category ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_category FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_subcategory ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_subcategory FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_category_society_isolation
                ON tickets_ticket_category
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_subcategory_society_isolation
                ON tickets_ticket_subcategory
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_ticket_society_isolation
                ON tickets_ticket
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE FUNCTION tickets_enforce_ticket_update()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF OLD.ticket_number <> ''
                        AND NEW.ticket_number IS DISTINCT FROM OLD.ticket_number THEN
                        RAISE EXCEPTION 'Allocated ticket numbers are immutable.';
                    END IF;
                    IF NEW.state_version <= OLD.state_version THEN
                        RAISE EXCEPTION 'Ticket state_version must increase on every update.';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER tickets_ticket_update_guard
                BEFORE UPDATE ON tickets_ticket
                FOR EACH ROW EXECUTE FUNCTION tickets_enforce_ticket_update();

                CREATE FUNCTION tickets_prevent_submitted_delete()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    IF OLD.status <> 'DRAFT' THEN
                        RAISE EXCEPTION 'Submitted tickets must be archived, not deleted.';
                    END IF;
                    RETURN OLD;
                END;
                $$;

                CREATE TRIGGER tickets_ticket_delete_guard
                BEFORE DELETE ON tickets_ticket
                FOR EACH ROW EXECUTE FUNCTION tickets_prevent_submitted_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS tickets_ticket_delete_guard ON tickets_ticket;
                DROP FUNCTION IF EXISTS tickets_prevent_submitted_delete();
                DROP TRIGGER IF EXISTS tickets_ticket_update_guard ON tickets_ticket;
                DROP FUNCTION IF EXISTS tickets_enforce_ticket_update();

                DROP POLICY IF EXISTS tickets_ticket_society_isolation
                    ON tickets_ticket;
                ALTER TABLE tickets_ticket NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_subcategory_society_isolation
                    ON tickets_ticket_subcategory;
                ALTER TABLE tickets_ticket_subcategory NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_subcategory DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_category_society_isolation
                    ON tickets_ticket_category;
                ALTER TABLE tickets_ticket_category NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_category DISABLE ROW LEVEL SECURITY;

                ALTER TABLE tickets_ticket
                    DROP CONSTRAINT IF EXISTS tickets_ticket_society_common_area_fk;
                ALTER TABLE tickets_ticket
                    DROP CONSTRAINT IF EXISTS tickets_ticket_society_unit_fk;
                ALTER TABLE tickets_ticket
                    DROP CONSTRAINT IF EXISTS tickets_ticket_society_subcategory_fk;
                ALTER TABLE tickets_ticket
                    DROP CONSTRAINT IF EXISTS tickets_ticket_society_category_workflow_fk;
                ALTER TABLE tickets_ticket_subcategory
                    DROP CONSTRAINT IF EXISTS tickets_subcategory_society_category_fk;
            """,
        ),
    ]
