# Generated by Django 5.2.17 on 2026-08-26 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('http_method', models.CharField(max_length=8)),
                ('route_template', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_idempotency_record',
                'ordering': ('society_id', 'created_at', 'id'),
                'indexes': [models.Index(fields=['society', 'expires_at'], name='tickets_idempotency_expiry')],
                'constraints': [models.UniqueConstraint(fields=('society', 'principal', 'http_method', 'route_template', 'idempotency_key'), name='tickets_idempotency_scope_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('response_status__isnull', True), ('status', 'IN_PROGRESS')), models.Q(('response_status__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='tickets_idempotency_response_state')],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_persona', models.CharField(max_length=32)),
                ('ticket_version', models.PositiveIntegerField()),
                ('previous_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('PENDING_ESTIMATE_APPROVAL', 'Pending estimate approval'), ('PENDING_RESIDENT_CONFIRMATION', 'Pending resident confirmation'), ('SUPERVISOR_TRIAGE', 'Supervisor triage'), ('UNDER_REVIEW', 'Under review'), ('IN_DISCUSSION', 'In discussion'), ('ACTION_TAKEN', 'Action taken'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('MERGED', 'Merged')], max_length=32)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('PENDING_ESTIMATE_APPROVAL', 'Pending estimate approval'), ('PENDING_RESIDENT_CONFIRMATION', 'Pending resident confirmation'), ('SUPERVISOR_TRIAGE', 'Supervisor triage'), ('UNDER_REVIEW', 'Under review'), ('IN_DISCUSSION', 'In discussion'), ('ACTION_TAKEN', 'Action taken'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('MERGED', 'Merged')], max_length=32)),
                ('event_type', models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted')], max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_events', to='tenancy.society')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_ticket_event',
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['society', 'ticket', 'occurred_at'], name='tickets_event_ticket_time'), models.Index(fields=['society', 'actor', 'occurred_at'], name='tickets_event_actor_time')],
                'constraints': [models.UniqueConstraint(fields=('society', 'ticket', 'ticket_version'), name='tickets_event_ticket_version_uniq'), models.CheckConstraint(condition=models.Q(('ticket_version__gte', 2)), name='tickets_event_transition_version')],
            },
        ),
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_year', models.PositiveSmallIntegerField()),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_number_sequences', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_ticket_number_sequence',
                'ordering': ('society_id', 'calendar_year'),
                'constraints': [models.UniqueConstraint(fields=('society', 'calendar_year'), name='tickets_sequence_society_year_uniq')],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_ticket_event
                ADD CONSTRAINT tickets_event_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_number_sequence ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_number_sequence FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_event ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_event FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_idempotency_record ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_idempotency_record FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_sequence_society_isolation
                ON tickets_ticket_number_sequence
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_event_society_isolation
                ON tickets_ticket_event
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_idempotency_society_isolation
                ON tickets_idempotency_record
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE FUNCTION tickets_reject_event_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'tickets_ticket_event is append-only'
                        USING ERRCODE = '55000';
                END;
                $$;

                CREATE TRIGGER tickets_ticket_event_immutable
                BEFORE UPDATE OR DELETE ON tickets_ticket_event
                FOR EACH ROW EXECUTE FUNCTION tickets_reject_event_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS tickets_ticket_event_immutable
                    ON tickets_ticket_event;
                DROP FUNCTION IF EXISTS tickets_reject_event_mutation();

                DROP POLICY IF EXISTS tickets_idempotency_society_isolation
                    ON tickets_idempotency_record;
                ALTER TABLE tickets_idempotency_record NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_idempotency_record DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_event_society_isolation
                    ON tickets_ticket_event;
                ALTER TABLE tickets_ticket_event NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_event DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_sequence_society_isolation
                    ON tickets_ticket_number_sequence;
                ALTER TABLE tickets_ticket_number_sequence NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_number_sequence DISABLE ROW LEVEL SECURITY;

                ALTER TABLE tickets_ticket_event
                    DROP CONSTRAINT IF EXISTS tickets_event_society_ticket_fk;
            """,
        ),
    ]
