# Generated by Django 5.2.17 on 2026-08-26 17:04

import datetime
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0002_idempotencyrecord_ticketevent_ticketnumbersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_key', models.CharField(max_length=128)),
                ('policy_version', models.PositiveIntegerField()),
                ('calendar_version', models.PositiveIntegerField()),
                ('society_timezone', models.CharField(max_length=64)),
                ('acceptance_duration', models.DurationField()),
                ('initial_resolution_duration', models.DurationField()),
                ('reopen_resolution_duration', models.DurationField()),
                ('l3_delay', models.DurationField()),
                ('permitted_pause_reasons', models.JSONField(blank=True, default=list)),
                ('estimate_decision_duration', models.DurationField()),
                ('max_assignment_failures', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_snapshots', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_sla_policy_snapshot',
                'ordering': ('society_id', 'policy_key', '-policy_version'),
            },
        ),
        migrations.CreateModel(
            name='SLAPolicyBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('P1', 'P1 Critical'), ('P2', 'P2 High'), ('P3', 'P3 Medium'), ('P4', 'P4 Low')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_bindings', to='tickets.ticketcategory')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_bindings', to='tenancy.society')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='tickets.slapolicysnapshot')),
            ],
            options={
                'db_table': 'tickets_sla_policy_binding',
                'ordering': ('society_id', 'category_id', 'priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SLACycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveSmallIntegerField()),
                ('cycle_type', models.CharField(choices=[('INITIAL', 'Initial'), ('REOPEN', 'Reopen')], max_length=8)),
                ('started_at', models.DateTimeField()),
                ('acceptance_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolution_deadline', models.DateTimeField()),
                ('pause_reason', models.CharField(blank=True, choices=[('APPROVER_DECISION', 'Approver decision'), ('RESIDENT_ACCESS_UNAVAILABLE', 'Resident access unavailable'), ('EXTERNAL_DEPENDENCY', 'External dependency')], default='', max_length=32)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_duration', models.DurationField(default=datetime.timedelta)),
                ('l1_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('l2_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('l3_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_failure_count', models.PositiveSmallIntegerField(default=0)),
                ('assignee_rejection_count', models.PositiveSmallIntegerField(default=0)),
                ('acceptance_timeout_count', models.PositiveSmallIntegerField(default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('MERGED', 'Merged')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_cycles', to='tenancy.society')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_cycles', to='tickets.ticket')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='tickets.slapolicysnapshot')),
            ],
            options={
                'db_table': 'tickets_sla_cycle',
                'ordering': ('society_id', 'ticket_id', 'cycle_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='slapolicysnapshot',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_sla_snapshot_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slapolicysnapshot',
            constraint=models.UniqueConstraint(fields=('society', 'policy_key', 'policy_version'), name='tickets_sla_snapshot_policy_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slapolicysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('calendar_version__gte', 1), ('policy_version__gte', 1)), name='tickets_sla_snapshot_positive_versions'),
        ),
        migrations.AddConstraint(
            model_name='slapolicysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('acceptance_duration__gt', datetime.timedelta(0)), ('initial_resolution_duration__gt', datetime.timedelta(0)), ('reopen_resolution_duration__gt', datetime.timedelta(0)), ('l3_delay__gte', datetime.timedelta(0)), ('estimate_decision_duration__gt', datetime.timedelta(0))), name='tickets_sla_snapshot_valid_durations'),
        ),
        migrations.AddConstraint(
            model_name='slapolicysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('max_assignment_failures__gte', 1)), name='tickets_sla_snapshot_positive_failures'),
        ),
        migrations.AddConstraint(
            model_name='slapolicybinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'category', 'priority'), name='tickets_sla_binding_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slapolicybinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('retired_at__isnull', True)), models.Q(('is_active', False), ('retired_at__isnull', False)), _connector='OR'), name='tickets_sla_binding_retirement_state'),
        ),
        migrations.AddIndex(
            model_name='slacycle',
            index=models.Index(condition=models.Q(('ended_at__isnull', True), ('paused_at__isnull', True)), fields=['society', 'resolution_deadline'], name='tickets_sla_cycle_due'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_sla_cycle_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.UniqueConstraint(fields=('society', 'ticket', 'cycle_number'), name='tickets_sla_cycle_ticket_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_number__gte', 1)), name='tickets_sla_cycle_positive_number'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_deadline__gt', models.F('started_at'))), name='tickets_sla_cycle_resolution_after_start'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pause_reason', ''), ('paused_at__isnull', True)), models.Q(models.Q(('pause_reason', ''), _negated=True), ('paused_at__isnull', False)), _connector='OR'), name='tickets_sla_cycle_pause_state'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('outcome', '')), models.Q(models.Q(('outcome', ''), _negated=True), ('ended_at__isnull', False)), _connector='OR'), name='tickets_sla_cycle_outcome_state'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(('total_paused_duration__gte', datetime.timedelta(0))), name='tickets_sla_cycle_nonnegative_pause'),
        ),
        migrations.AddConstraint(
            model_name='slacycle',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_failure_count__gte', django.db.models.expressions.CombinedExpression(models.F('assignee_rejection_count'), '+', models.F('acceptance_timeout_count')))), name='tickets_sla_cycle_failure_counters'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_sla_policy_binding
                ADD CONSTRAINT tickets_sla_binding_society_category_fk
                FOREIGN KEY (society_id, category_id)
                REFERENCES tickets_ticket_category (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_sla_policy_binding
                ADD CONSTRAINT tickets_sla_binding_society_snapshot_fk
                FOREIGN KEY (society_id, snapshot_id)
                REFERENCES tickets_sla_policy_snapshot (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_sla_cycle
                ADD CONSTRAINT tickets_sla_cycle_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_sla_cycle
                ADD CONSTRAINT tickets_sla_cycle_society_snapshot_fk
                FOREIGN KEY (society_id, snapshot_id)
                REFERENCES tickets_sla_policy_snapshot (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_sla_policy_snapshot ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_policy_snapshot FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_policy_binding ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_policy_binding FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_cycle ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_cycle FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_sla_snapshot_society_isolation
                ON tickets_sla_policy_snapshot
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_sla_binding_society_isolation
                ON tickets_sla_policy_binding
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_sla_cycle_society_isolation
                ON tickets_sla_cycle
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE FUNCTION tickets_reject_sla_snapshot_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'tickets_sla_policy_snapshot is immutable'
                        USING ERRCODE = '55000';
                END;
                $$;

                CREATE TRIGGER tickets_sla_snapshot_immutable
                BEFORE UPDATE OR DELETE ON tickets_sla_policy_snapshot
                FOR EACH ROW EXECUTE FUNCTION tickets_reject_sla_snapshot_mutation();

                CREATE FUNCTION tickets_reject_sla_cycle_delete()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'tickets_sla_cycle history cannot be deleted'
                        USING ERRCODE = '55000';
                END;
                $$;

                CREATE TRIGGER tickets_sla_cycle_retain_history
                BEFORE DELETE ON tickets_sla_cycle
                FOR EACH ROW EXECUTE FUNCTION tickets_reject_sla_cycle_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS tickets_sla_cycle_retain_history
                    ON tickets_sla_cycle;
                DROP FUNCTION IF EXISTS tickets_reject_sla_cycle_delete();
                DROP TRIGGER IF EXISTS tickets_sla_snapshot_immutable
                    ON tickets_sla_policy_snapshot;
                DROP FUNCTION IF EXISTS tickets_reject_sla_snapshot_mutation();

                DROP POLICY IF EXISTS tickets_sla_cycle_society_isolation
                    ON tickets_sla_cycle;
                ALTER TABLE tickets_sla_cycle NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_cycle DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_sla_binding_society_isolation
                    ON tickets_sla_policy_binding;
                ALTER TABLE tickets_sla_policy_binding NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_policy_binding DISABLE ROW LEVEL SECURITY;
                DROP POLICY IF EXISTS tickets_sla_snapshot_society_isolation
                    ON tickets_sla_policy_snapshot;
                ALTER TABLE tickets_sla_policy_snapshot NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_sla_policy_snapshot DISABLE ROW LEVEL SECURITY;

                ALTER TABLE tickets_sla_cycle
                    DROP CONSTRAINT IF EXISTS tickets_sla_cycle_society_snapshot_fk;
                ALTER TABLE tickets_sla_cycle
                    DROP CONSTRAINT IF EXISTS tickets_sla_cycle_society_ticket_fk;
                ALTER TABLE tickets_sla_policy_binding
                    DROP CONSTRAINT IF EXISTS tickets_sla_binding_society_snapshot_fk;
                ALTER TABLE tickets_sla_policy_binding
                    DROP CONSTRAINT IF EXISTS tickets_sla_binding_society_category_fk;
            """,
        ),
    ]
