# Generated by Django 5.2.17 on 2026-08-27 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0008_governancediscussion_and_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.CreateModel(
            name='GovernanceActionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('evidence_policy', models.CharField(choices=[('NO_EXTERNAL_EVIDENCE', 'External evidence is not yet supported')], default='NO_EXTERNAL_EVIDENCE', max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_governance_actions', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_action_records', to='tenancy.society')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='governance_action_record', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_governance_action_record',
                'ordering': ('society_id', 'recorded_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('society', 'id'), name='tickets_gov_action_society_id_uniq')],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_governance_action_record
                ADD CONSTRAINT tickets_gov_action_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_governance_action_record ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_governance_action_record FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_gov_action_society_isolation
                ON tickets_governance_action_record
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tickets_gov_action_society_isolation
                    ON tickets_governance_action_record;
                ALTER TABLE tickets_governance_action_record NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_governance_action_record DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_governance_action_record
                    DROP CONSTRAINT IF EXISTS tickets_gov_action_society_ticket_fk;
            """,
        ),
    ]
