# Generated by Django 5.2.17 on 2026-08-27 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0009_alter_ticketevent_event_type_governanceactionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('IN_HOUSE', 'In-house technician'), ('VENDOR', 'Vendor contract')], max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_deadline', models.DateTimeField()),
                ('state', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('ENDED', 'Ended')], default='OFFERED', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to='tenancy.society')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to='tenancy.technicianprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tickets.ticket')),
                ('vendor_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to='tenancy.vendorcontract')),
            ],
            options={
                'db_table': 'tickets_ticket_assignment',
                'ordering': ('society_id', 'ticket_id', 'assigned_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VendorStaffAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('ACCEPTED', 'Accepted'), ('ENDED', 'Ended')], default='ALLOCATED', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_vendor_allocations', to=settings.AUTH_USER_MODEL)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_vendor_staff', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_staff_allocations', to='tickets.ticketassignment')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_staff_allocations', to='tenancy.society')),
                ('staff_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_allocations', to='tenancy.vendorstaffmembership')),
            ],
            options={
                'db_table': 'tickets_vendor_staff_allocation',
                'ordering': ('society_id', 'assignment_id', 'allocated_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_assignment_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ENDED'), _negated=True), fields=('society', 'ticket'), name='tickets_assignment_one_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'IN_HOUSE'), ('technician__isnull', False), ('vendor_contract__isnull', True)), models.Q(('target_type', 'VENDOR'), ('technician__isnull', True), ('vendor_contract__isnull', False)), _connector='OR'), name='tickets_assignment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', False), ('ended_reason__gt', ''), ('state', 'ENDED')), models.Q(models.Q(('state', 'ENDED'), _negated=True), ('ended_at__isnull', True), ('ended_reason', '')), _connector='OR'), name='tickets_assignment_end_metadata'),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True), ('state', 'OFFERED')), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('state__in', ('ACCEPTED', 'ENDED'))), _connector='OR'), name='tickets_assignment_acceptance_metadata'),
        ),
        migrations.AddConstraint(
            model_name='vendorstaffallocation',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_vendor_alloc_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendorstaffallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ENDED'), _negated=True), fields=('society', 'assignment'), name='tickets_vendor_alloc_one_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendorstaffallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', False), ('ended_reason__gt', ''), ('state', 'ENDED')), models.Q(models.Q(('state', 'ENDED'), _negated=True), ('ended_at__isnull', True), ('ended_reason', '')), _connector='OR'), name='tickets_vendor_alloc_end_metadata'),
        ),
        migrations.AddConstraint(
            model_name='vendorstaffallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True), ('state', 'ALLOCATED')), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('state__in', ('ACCEPTED', 'ENDED'))), _connector='OR'), name='tickets_vendor_alloc_acceptance_metadata'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE tickets_ticket_assignment
                ADD CONSTRAINT tickets_assignment_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_assignment
                ADD CONSTRAINT tickets_assignment_society_technician_fk
                FOREIGN KEY (society_id, technician_id)
                REFERENCES tenancy_technician_profile (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_assignment
                ADD CONSTRAINT tickets_assignment_society_vendor_contract_fk
                FOREIGN KEY (society_id, vendor_contract_id)
                REFERENCES tenancy_vendor_contract (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_vendor_staff_allocation
                ADD CONSTRAINT tickets_vendor_alloc_society_assignment_fk
                FOREIGN KEY (society_id, assignment_id)
                REFERENCES tickets_ticket_assignment (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_vendor_staff_allocation
                ADD CONSTRAINT tickets_vendor_alloc_society_staff_fk
                FOREIGN KEY (society_id, staff_membership_id)
                REFERENCES tenancy_vendor_staff_membership (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_assignment ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_assignment FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_vendor_staff_allocation ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_vendor_staff_allocation FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_assignment_society_isolation
                ON tickets_ticket_assignment
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );

                CREATE POLICY tickets_vendor_alloc_society_isolation
                ON tickets_vendor_staff_allocation
                USING (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                )
                WITH CHECK (
                    society_id = CASE
                        WHEN current_setting('app.society_id', true) ~*
                            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        THEN current_setting('app.society_id', true)::uuid
                        ELSE NULL
                    END
                );
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tickets_vendor_alloc_society_isolation
                    ON tickets_vendor_staff_allocation;
                DROP POLICY IF EXISTS tickets_assignment_society_isolation
                    ON tickets_ticket_assignment;
                ALTER TABLE tickets_vendor_staff_allocation NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_vendor_staff_allocation DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_assignment NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_assignment DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_vendor_staff_allocation
                    DROP CONSTRAINT IF EXISTS tickets_vendor_alloc_society_staff_fk;
                ALTER TABLE tickets_vendor_staff_allocation
                    DROP CONSTRAINT IF EXISTS tickets_vendor_alloc_society_assignment_fk;
                ALTER TABLE tickets_ticket_assignment
                    DROP CONSTRAINT IF EXISTS tickets_assignment_society_vendor_contract_fk;
                ALTER TABLE tickets_ticket_assignment
                    DROP CONSTRAINT IF EXISTS tickets_assignment_society_technician_fk;
                ALTER TABLE tickets_ticket_assignment
                    DROP CONSTRAINT IF EXISTS tickets_assignment_society_ticket_fk;
            """,
        ),
    ]
