# Generated by Django 5.2.17 on 2026-08-27 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0011_ticket_assigned_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticketassignment',
            name='tickets_assignment_acceptance_metadata',
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='ticketassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True), ('state', 'OFFERED')), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('state', 'ACCEPTED')), models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True), ('state', 'ENDED')), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('state', 'ENDED')), _connector='OR'), name='tickets_assignment_acceptance_metadata'),
        ),
    ]
