# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_in_house_assignment_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TICKET_SUBMITTED", "Ticket submitted"),
                    ("TICKET_CANCELLED", "Ticket cancelled"),
                    ("TICKET_ASSIGNED", "Ticket assigned"),
                    ("TICKET_ASSIGNMENT_ACCEPTED", "Ticket assignment accepted"),
                    ("TICKET_ASSIGNMENT_REJECTED", "Ticket assignment rejected"),
                    ("VENDOR_WORKER_ALLOCATED", "Vendor worker allocated"),
                    ("GOVERNANCE_REVIEW_BEGUN", "Governance review begun"),
                    ("GOVERNANCE_DISCUSSION_OPENED", "Governance discussion opened"),
                    ("GOVERNANCE_ACTION_RECORDED", "Governance action recorded"),
                ],
                max_length=64,
            ),
        ),
    ]