# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_vendor_worker_allocated_event"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vendorstaffallocation",
            name="tickets_vendor_alloc_acceptance_metadata",
        ),
        migrations.AddConstraint(
            model_name="vendorstaffallocation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("accepted_by__isnull", True),
                        ("state", "ALLOCATED"),
                    )
                    | models.Q(
                        ("accepted_at__isnull", False),
                        ("accepted_by__isnull", False),
                        ("state", "ACCEPTED"),
                    )
                    | (
                        models.Q(("state", "ENDED"))
                        & (
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                            )
                            | models.Q(
                                ("accepted_at__isnull", False),
                                ("accepted_by__isnull", False),
                            )
                        )
                    )
                ),
                name="tickets_vendor_alloc_acceptance_metadata",
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TICKET_SUBMITTED", "Ticket submitted"),
                    ("TICKET_CANCELLED", "Ticket cancelled"),
                    ("TICKET_ASSIGNED", "Ticket assigned"),
                    ("TICKET_ASSIGNMENT_ACCEPTED", "Ticket assignment accepted"),
                    ("TICKET_ASSIGNMENT_REJECTED", "Ticket assignment rejected"),
                    ("VENDOR_WORKER_ALLOCATED", "Vendor worker allocated"),
                    ("VENDOR_WORKER_REPLACED", "Vendor worker replaced"),
                    ("GOVERNANCE_REVIEW_BEGUN", "Governance review begun"),
                    ("GOVERNANCE_DISCUSSION_OPENED", "Governance discussion opened"),
                    ("GOVERNANCE_ACTION_RECORDED", "Governance action recorded"),
                ],
                max_length=64,
            ),
        ),
    ]