# Generated by Django 5.2.17 on 2026-08-28 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0015_ticket_work_started_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('VENDOR_WORKER_ALLOCATED', 'Vendor worker allocated'), ('VENDOR_WORKER_REPLACED', 'Vendor worker replaced'), ('TICKET_WORK_STARTED', 'Ticket work started'), ('TICKET_COMPLETION_REQUESTED', 'Ticket completion requested'), ('TICKET_RESOLVED', 'Ticket resolved'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.CreateModel(
            name='TicketCompletionChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_notes', models.TextField()),
                ('otp_code', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_challenges', to='tickets.ticketassignment')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumed_completion_challenges', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_completion_challenges', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_completion_challenges', to='tenancy.society')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_challenges', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_ticket_completion_challenge',
                'ordering': ('society_id', 'ticket_id', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('society', 'id'), name='tickets_challenge_society_id_uniq'), models.UniqueConstraint(fields=('society', 'ticket', 'id'), name='tickets_challenge_society_ticket_id_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('consumed_at__isnull', False), ('consumed_by__isnull', False), ('is_consumed', True)), models.Q(('consumed_at__isnull', True), ('consumed_by__isnull', True), ('is_consumed', False)), _connector='OR'), name='tickets_challenge_consumed_metadata')],
            },
        ),
    ]
