# Generated by Django 5.2.17 on 2026-08-28 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0016_ticket_completion_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('VENDOR_WORKER_ALLOCATED', 'Vendor worker allocated'), ('VENDOR_WORKER_REPLACED', 'Vendor worker replaced'), ('TICKET_WORK_STARTED', 'Ticket work started'), ('TICKET_COMPLETION_REQUESTED', 'Ticket completion requested'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_ESTIMATE_SUBMITTED', 'Ticket estimate submitted'), ('TICKET_ESTIMATE_APPROVED', 'Ticket estimate approved'), ('TICKET_ESTIMATE_REJECTED', 'Ticket estimate rejected'), ('TICKET_ESTIMATE_WITHDRAWN', 'Ticket estimate withdrawn'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.CreateModel(
            name='TicketEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=16)),
                ('cost_responsibility', models.CharField(choices=[('RESIDENT_UNIT', 'Resident unit'), ('SOCIETY', 'Society'), ('NO_CHARGE', 'No charge')], max_length=16)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='tickets.ticketassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ticket_estimates', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_ticket_estimates', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_estimates', to='tenancy.society')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_ticket_estimate',
                'ordering': ('society_id', 'ticket_id', '-version'),
            },
        ),
        migrations.CreateModel(
            name='TicketEstimateLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.ticketestimate')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_estimate_line_items', to='tenancy.society')),
            ],
            options={
                'db_table': 'tickets_ticket_estimate_line_item',
                'ordering': ('society_id', 'estimate_id', 'created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketestimate',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_estimate_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketestimate',
            constraint=models.UniqueConstraint(fields=('society', 'ticket', 'version'), name='tickets_estimate_society_ticket_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketestimate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('society', 'ticket'), name='tickets_estimate_one_pending_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketestimate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ['APPROVED', 'REJECTED', 'WITHDRAWN'])), models.Q(('status__in', ['APPROVED', 'REJECTED', 'WITHDRAWN']), _negated=True), _connector='OR'), name='tickets_estimate_decided_metadata'),
        ),
        migrations.AddConstraint(
            model_name='ticketestimatelineitem',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_estimate_item_society_id_uniq'),
        ),
    ]
