# Generated by Django 5.2.17 on 2026-08-28 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0019_ticket_supervisor_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('VENDOR_WORKER_ALLOCATED', 'Vendor worker allocated'), ('VENDOR_WORKER_REPLACED', 'Vendor worker replaced'), ('TICKET_WORK_STARTED', 'Ticket work started'), ('TICKET_COMPLETION_REQUESTED', 'Ticket completion requested'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_ESTIMATE_SUBMITTED', 'Ticket estimate submitted'), ('TICKET_ESTIMATE_APPROVED', 'Ticket estimate approved'), ('TICKET_ESTIMATE_REJECTED', 'Ticket estimate rejected'), ('TICKET_ESTIMATE_WITHDRAWN', 'Ticket estimate withdrawn'), ('TICKET_REOPENED', 'Ticket reopened'), ('TICKET_CLOSED', 'Ticket closed'), ('TICKET_TRIAGE_REASSIGNED', 'Ticket triage reassigned'), ('TICKET_TRIAGE_RESUMED_OVERRIDE', 'Ticket triage resumed by supervisor override'), ('TICKET_RESOLVED_OVERRIDE', 'Ticket resolved by supervisor override'), ('TICKET_RATED', 'Ticket rated'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('timeliness_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('technician_behavior_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_ticket_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_feedbacks', to='tenancy.society')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_feedbacks', to='tenancy.technicianprofile')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='tickets.ticket')),
                ('vendor_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_feedbacks', to='tenancy.vendorcontract')),
            ],
            options={
                'db_table': 'tickets_ticket_feedback',
                'ordering': ('society_id', 'ticket_id', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_feedback_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.UniqueConstraint(fields=('society', 'ticket'), name='tickets_feedback_society_ticket_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.UniqueConstraint(fields=('society', 'ticket', 'id'), name='tickets_feedback_society_ticket_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('overall_rating__gte', 1), ('overall_rating__lte', 5)), name='tickets_feedback_overall_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('timeliness_rating__isnull', True), models.Q(('timeliness_rating__gte', 1), ('timeliness_rating__lte', 5)), _connector='OR'), name='tickets_feedback_timeliness_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('quality_rating__isnull', True), models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 5)), _connector='OR'), name='tickets_feedback_quality_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='ticketfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('technician_behavior_rating__isnull', True), models.Q(('technician_behavior_rating__gte', 1), ('technician_behavior_rating__lte', 5)), _connector='OR'), name='tickets_feedback_behavior_rating_range'),
        ),
    ]
