# Generated by Django 5.2.17 on 2026-08-28 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_vendor_vendorcontract_vendorstaffmembership_and_more'),
        ('tickets', '0020_ticket_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('VENDOR_WORKER_ALLOCATED', 'Vendor worker allocated'), ('VENDOR_WORKER_REPLACED', 'Vendor worker replaced'), ('TICKET_WORK_STARTED', 'Ticket work started'), ('TICKET_COMPLETION_REQUESTED', 'Ticket completion requested'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_ESTIMATE_SUBMITTED', 'Ticket estimate submitted'), ('TICKET_ESTIMATE_APPROVED', 'Ticket estimate approved'), ('TICKET_ESTIMATE_REJECTED', 'Ticket estimate rejected'), ('TICKET_ESTIMATE_WITHDRAWN', 'Ticket estimate withdrawn'), ('TICKET_REOPENED', 'Ticket reopened'), ('TICKET_CLOSED', 'Ticket closed'), ('TICKET_TRIAGE_REASSIGNED', 'Ticket triage reassigned'), ('TICKET_TRIAGE_RESUMED_OVERRIDE', 'Ticket triage resumed by supervisor override'), ('TICKET_RESOLVED_OVERRIDE', 'Ticket resolved by supervisor override'), ('TICKET_RATED', 'Ticket rated'), ('TICKET_MERGED', 'Ticket merged'), ('TICKET_MERGE_ATTACHED', 'Secondary ticket merged into this ticket'), ('TICKET_UNMERGED', 'Ticket unmerged'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded')], max_length=64),
        ),
        migrations.CreateModel(
            name='TicketMergeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('previous_secondary_status', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('unmerged_at', models.DateTimeField(blank=True, null=True)),
                ('unmerge_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_ticket_merges', to=settings.AUTH_USER_MODEL)),
                ('primary_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_secondary_records', to='tickets.ticket')),
                ('secondary_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_records', to='tickets.ticket')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_merge_records', to='tenancy.society')),
                ('unmerged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_ticket_unmerges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets_ticket_merge_record',
                'ordering': ('society_id', 'primary_ticket_id', '-merged_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketmergerecord',
            constraint=models.UniqueConstraint(fields=('society', 'id'), name='tickets_merge_society_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketmergerecord',
            constraint=models.UniqueConstraint(fields=('society', 'primary_ticket', 'id'), name='tickets_merge_society_primary_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketmergerecord',
            constraint=models.UniqueConstraint(fields=('society', 'secondary_ticket', 'id'), name='tickets_merge_society_secondary_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketmergerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('society', 'secondary_ticket'), name='tickets_merge_one_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticketmergerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('unmerge_reason', ''), ('unmerged_at__isnull', True), ('unmerged_by__isnull', True)), models.Q(('is_active', False), ('unmerge_reason__gt', ''), ('unmerged_at__isnull', False), ('unmerged_by__isnull', False)), _connector='OR'), name='tickets_merge_unmerge_metadata'),
        ),
    ]
