# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


_SOCIETY_POLICY = """
    society_id = CASE
        WHEN current_setting('app.society_id', true) ~*
            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        THEN current_setting('app.society_id', true)::uuid
        ELSE NULL
    END
"""


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_ticket_merge_record"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticketestimate",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("subtotal_amount__gte", 0))
                    & models.Q(("tax_amount__gte", 0))
                    & models.Q(("total_amount__gte", 0))
                    & models.Q(
                        ("total_amount", models.F("subtotal_amount") + models.F("tax_amount"))
                    )
                ),
                name="tickets_estimate_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketestimatelineitem",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("quantity__gt", 0))
                    & models.Q(("unit_cost__gte", 0))
                    & models.Q(("total_cost__gte", 0))
                    & models.Q(
                        ("total_cost", models.F("quantity") * models.F("unit_cost"))
                    )
                ),
                name="tickets_estimate_item_amounts_valid",
            ),
        ),
        migrations.RunSQL(
            sql=f"""
                ALTER TABLE tickets_ticket_completion_challenge
                ADD CONSTRAINT tickets_challenge_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_completion_challenge
                ADD CONSTRAINT tickets_challenge_society_assignment_fk
                FOREIGN KEY (society_id, assignment_id)
                REFERENCES tickets_ticket_assignment (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_estimate
                ADD CONSTRAINT tickets_estimate_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_estimate
                ADD CONSTRAINT tickets_estimate_society_assignment_fk
                FOREIGN KEY (society_id, assignment_id)
                REFERENCES tickets_ticket_assignment (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_estimate_line_item
                ADD CONSTRAINT tickets_estimate_item_society_estimate_fk
                FOREIGN KEY (society_id, estimate_id)
                REFERENCES tickets_ticket_estimate (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_feedback
                ADD CONSTRAINT tickets_feedback_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_feedback
                ADD CONSTRAINT tickets_feedback_society_technician_fk
                FOREIGN KEY (society_id, technician_id)
                REFERENCES tenancy_technician_profile (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_feedback
                ADD CONSTRAINT tickets_feedback_society_vendor_contract_fk
                FOREIGN KEY (society_id, vendor_contract_id)
                REFERENCES tenancy_vendor_contract (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_merge_record
                ADD CONSTRAINT tickets_merge_society_primary_ticket_fk
                FOREIGN KEY (society_id, primary_ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_merge_record
                ADD CONSTRAINT tickets_merge_society_secondary_ticket_fk
                FOREIGN KEY (society_id, secondary_ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_completion_challenge ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_completion_challenge FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate_line_item ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate_line_item FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_feedback ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_feedback FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_merge_record ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_merge_record FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_challenge_society_isolation
                ON tickets_ticket_completion_challenge
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});

                CREATE POLICY tickets_estimate_society_isolation
                ON tickets_ticket_estimate
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});

                CREATE POLICY tickets_estimate_item_society_isolation
                ON tickets_ticket_estimate_line_item
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});

                CREATE POLICY tickets_feedback_society_isolation
                ON tickets_ticket_feedback
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});

                CREATE POLICY tickets_merge_society_isolation
                ON tickets_ticket_merge_record
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});

                CREATE FUNCTION tickets_prevent_feedback_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'Ticket feedback is immutable';
                END;
                $$;

                CREATE TRIGGER tickets_feedback_immutable
                BEFORE UPDATE OR DELETE ON tickets_ticket_feedback
                FOR EACH ROW EXECUTE FUNCTION tickets_prevent_feedback_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS tickets_feedback_immutable ON tickets_ticket_feedback;
                DROP FUNCTION IF EXISTS tickets_prevent_feedback_mutation();

                DROP POLICY IF EXISTS tickets_merge_society_isolation ON tickets_ticket_merge_record;
                DROP POLICY IF EXISTS tickets_feedback_society_isolation ON tickets_ticket_feedback;
                DROP POLICY IF EXISTS tickets_estimate_item_society_isolation ON tickets_ticket_estimate_line_item;
                DROP POLICY IF EXISTS tickets_estimate_society_isolation ON tickets_ticket_estimate;
                DROP POLICY IF EXISTS tickets_challenge_society_isolation ON tickets_ticket_completion_challenge;

                ALTER TABLE tickets_ticket_merge_record NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_merge_record DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_feedback NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_feedback DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate_line_item NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate_line_item DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_estimate DISABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_completion_challenge NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_completion_challenge DISABLE ROW LEVEL SECURITY;

                ALTER TABLE tickets_ticket_merge_record DROP CONSTRAINT IF EXISTS tickets_merge_society_secondary_ticket_fk;
                ALTER TABLE tickets_ticket_merge_record DROP CONSTRAINT IF EXISTS tickets_merge_society_primary_ticket_fk;
                ALTER TABLE tickets_ticket_feedback DROP CONSTRAINT IF EXISTS tickets_feedback_society_vendor_contract_fk;
                ALTER TABLE tickets_ticket_feedback DROP CONSTRAINT IF EXISTS tickets_feedback_society_technician_fk;
                ALTER TABLE tickets_ticket_feedback DROP CONSTRAINT IF EXISTS tickets_feedback_society_ticket_fk;
                ALTER TABLE tickets_ticket_estimate_line_item DROP CONSTRAINT IF EXISTS tickets_estimate_item_society_estimate_fk;
                ALTER TABLE tickets_ticket_estimate DROP CONSTRAINT IF EXISTS tickets_estimate_society_assignment_fk;
                ALTER TABLE tickets_ticket_estimate DROP CONSTRAINT IF EXISTS tickets_estimate_society_ticket_fk;
                ALTER TABLE tickets_ticket_completion_challenge DROP CONSTRAINT IF EXISTS tickets_challenge_society_assignment_fk;
                ALTER TABLE tickets_ticket_completion_challenge DROP CONSTRAINT IF EXISTS tickets_challenge_society_ticket_fk;
            """,
        ),
    ]