# Generated by Django 5.2.17 on 2026-08-30

from django.contrib.auth.hashers import make_password
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def hash_existing_otps(apps, schema_editor):
    TicketCompletionChallenge = apps.get_model("tickets", "TicketCompletionChallenge")
    for challenge in TicketCompletionChallenge.objects.iterator():
        challenge.otp_hash = make_password(challenge.otp_code)
        challenge.save(update_fields=("otp_hash",))


def prevent_otp_recovery(apps, schema_editor):
    raise IrreversibleError(
        "Plaintext completion OTPs were intentionally removed and cannot be recovered."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0022_ticket_lifecycle_tenant_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcompletionchallenge",
            name="otp_hash",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(hash_existing_otps, prevent_otp_recovery),
        migrations.RemoveField(
            model_name="ticketcompletionchallenge",
            name="otp_code",
        ),
        migrations.AlterField(
            model_name="ticketcompletionchallenge",
            name="otp_hash",
            field=models.CharField(max_length=128),
        ),
    ]