# Generated by Django 5.2.17 on 2026-08-30

import uuid

from django.db import migrations, models
import django.db.models.deletion


_SOCIETY_POLICY = """
    society_id = CASE
        WHEN current_setting('app.society_id', true) ~*
            '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        THEN current_setting('app.society_id', true)::uuid
        ELSE NULL
    END
"""


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_hash_ticket_completion_challenge_otp"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticketevent",
            constraint=models.UniqueConstraint(
                fields=("society", "id"),
                name="tickets_event_society_id_uniq",
            ),
        ),
        migrations.CreateModel(
            name="TicketOutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "SERVICE_COMPLETION_NOTIFICATION_REQUESTED",
                                "Service completion notification requested",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion_challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="tickets.ticketcompletionchallenge",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_outbox_events",
                        to="tenancy.society",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "ticket_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="tickets.ticketevent",
                    ),
                ),
            ],
            options={
                "db_table": "tickets_ticket_outbox_event",
                "ordering": ("society_id", "created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.UniqueConstraint(
                fields=("society", "id"),
                name="tickets_outbox_society_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.UniqueConstraint(
                fields=("society", "ticket_event"),
                name="tickets_outbox_society_event_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketoutboxevent",
            index=models.Index(
                fields=("society", "event_type", "created_at"),
                name="tickets_outbox_pending_idx",
            ),
        ),
        migrations.RunSQL(
            sql=f"""
                ALTER TABLE tickets_ticket_outbox_event
                ADD CONSTRAINT tickets_outbox_society_ticket_fk
                FOREIGN KEY (society_id, ticket_id)
                REFERENCES tickets_ticket (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_outbox_event
                ADD CONSTRAINT tickets_outbox_society_event_fk
                FOREIGN KEY (society_id, ticket_event_id)
                REFERENCES tickets_ticket_event (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_outbox_event
                ADD CONSTRAINT tickets_outbox_society_challenge_fk
                FOREIGN KEY (society_id, completion_challenge_id)
                REFERENCES tickets_ticket_completion_challenge (society_id, id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE tickets_ticket_outbox_event ENABLE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_outbox_event FORCE ROW LEVEL SECURITY;

                CREATE POLICY tickets_outbox_society_isolation
                ON tickets_ticket_outbox_event
                USING ({_SOCIETY_POLICY})
                WITH CHECK ({_SOCIETY_POLICY});
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tickets_outbox_society_isolation ON tickets_ticket_outbox_event;

                ALTER TABLE tickets_ticket_outbox_event NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE tickets_ticket_outbox_event DISABLE ROW LEVEL SECURITY;

                ALTER TABLE tickets_ticket_outbox_event DROP CONSTRAINT IF EXISTS tickets_outbox_society_challenge_fk;
                ALTER TABLE tickets_ticket_outbox_event DROP CONSTRAINT IF EXISTS tickets_outbox_society_event_fk;
                ALTER TABLE tickets_ticket_outbox_event DROP CONSTRAINT IF EXISTS tickets_outbox_society_ticket_fk;
            """,
        ),
    ]