# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_ticket_outbox_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="attempts_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="available_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="last_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="state_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CLAIMED", "Claimed"),
                    ("DELIVERED", "Delivered"),
                    ("DEAD_LETTER", "Dead letter"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("state_version__gte", 1)),
                name="tickets_outbox_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts_count__lte", models.F("max_attempts")))
                & models.Q(("max_attempts__gte", 1)),
                name="tickets_outbox_attempt_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_expires_at__isnull", False),
                        ("claim_token__isnull", False),
                        ("claimed_at__isnull", False),
                        ("status", "CLAIMED"),
                    ),
                    models.Q(
                        models.Q(("status", "CLAIMED"), _negated=True),
                        ("claim_expires_at__isnull", True),
                        ("claim_token__isnull", True),
                        ("claimed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tickets_outbox_claim_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("dead_lettered_at__isnull", True),
                        ("delivered_at__isnull", False),
                        ("status", "DELIVERED"),
                    ),
                    models.Q(
                        ("dead_lettered_at__isnull", False),
                        ("delivered_at__isnull", True),
                        ("status", "DEAD_LETTER"),
                    ),
                    models.Q(
                        ("dead_lettered_at__isnull", True),
                        ("delivered_at__isnull", True),
                        ("status__in", ["PENDING", "CLAIMED"]),
                    ),
                    _connector="OR",
                ),
                name="tickets_outbox_terminal_state",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketoutboxevent",
            index=models.Index(
                fields=("society", "status", "available_at"),
                name="tickets_outbox_claim_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketoutboxevent",
            index=models.Index(
                fields=("society", "status", "claim_expires_at"),
                name="tickets_outbox_claim_lease_idx",
            ),
        ),
    ]