# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0025_ticket_outbox_delivery_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcompletionchallenge",
            name="delivery_capsule_name",
            field=models.CharField(blank=True, default="", max_length=127),
        ),
    ]