# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0026_ticket_completion_delivery_capsule"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ticketoutboxevent",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketoutboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CLAIMED", "Claimed"),
                    ("SUBMITTED", "Submitted"),
                    ("DELIVERED", "Delivered"),
                    ("DEAD_LETTER", "Dead letter"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="ticketoutboxevent",
            name="tickets_outbox_terminal_state",
        ),
        migrations.AddConstraint(
            model_name="ticketoutboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("dead_lettered_at__isnull", True),
                        ("delivered_at__isnull", False),
                        ("status", "DELIVERED"),
                    ),
                    models.Q(
                        ("dead_lettered_at__isnull", True),
                        ("delivered_at__isnull", True),
                        ("provider_message_id__gt", ""),
                        ("status", "SUBMITTED"),
                        ("submitted_at__isnull", False),
                    ),
                    models.Q(
                        ("dead_lettered_at__isnull", False),
                        ("delivered_at__isnull", True),
                        ("status", "DEAD_LETTER"),
                    ),
                    models.Q(
                        ("dead_lettered_at__isnull", True),
                        ("delivered_at__isnull", True),
                        ("provider_message_id", ""),
                        ("status__in", ["PENDING", "CLAIMED"]),
                        ("submitted_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tickets_outbox_terminal_state",
            ),
        ),
    ]