# Generated by Django 5.2.17 on 2026-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_ticket_attachment_upload_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('TICKET_SUBMITTED', 'Ticket submitted'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_ASSIGNMENT_ACCEPTED', 'Ticket assignment accepted'), ('TICKET_ASSIGNMENT_REJECTED', 'Ticket assignment rejected'), ('VENDOR_WORKER_ALLOCATED', 'Vendor worker allocated'), ('VENDOR_WORKER_REPLACED', 'Vendor worker replaced'), ('TICKET_WORK_STARTED', 'Ticket work started'), ('TICKET_COMPLETION_REQUESTED', 'Ticket completion requested'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_ESTIMATE_SUBMITTED', 'Ticket estimate submitted'), ('TICKET_ESTIMATE_APPROVED', 'Ticket estimate approved'), ('TICKET_ESTIMATE_REJECTED', 'Ticket estimate rejected'), ('TICKET_ESTIMATE_WITHDRAWN', 'Ticket estimate withdrawn'), ('TICKET_REOPENED', 'Ticket reopened'), ('TICKET_CLOSED', 'Ticket closed'), ('TICKET_TRIAGE_REASSIGNED', 'Ticket triage reassigned'), ('TICKET_TRIAGE_RESUMED_OVERRIDE', 'Ticket triage resumed by supervisor override'), ('TICKET_RESOLVED_OVERRIDE', 'Ticket resolved by supervisor override'), ('TICKET_RATED', 'Ticket rated'), ('TICKET_MERGED', 'Ticket merged'), ('TICKET_MERGE_ATTACHED', 'Secondary ticket merged into this ticket'), ('TICKET_UNMERGED', 'Ticket unmerged'), ('GOVERNANCE_REVIEW_BEGUN', 'Governance review begun'), ('GOVERNANCE_DISCUSSION_OPENED', 'Governance discussion opened'), ('GOVERNANCE_ACTION_RECORDED', 'Governance action recorded'), ('TICKET_ATTACHMENT_UPLOAD_SLOT_ISSUED', 'Ticket attachment upload slot issued'), ('TICKET_ATTACHMENT_PROMOTED', 'Ticket attachment promoted to available'), ('TICKET_ATTACHMENT_REJECTED', 'Ticket attachment rejected')], max_length=64),
        ),
    ]
