# Generated by Django 5.2.17 on 2026-08-29 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailAuthChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('ACTIVATION', 'Activation'), ('PASSWORD_RESET', 'Password reset')], max_length=32)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_auth_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_email_auth_challenge',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='identity_email_auth_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='identity_email_auth_future_expiry')],
            },
        ),
    ]
